---
title: "The Chase"
author: "Adam J Campbell"
date: "04/09/2020"
output: html_document
---

```{r scrape data, message=FALSE, warning=FALSE}
source("ETL.R")
players <- getPlayerData()
episodes <- getEpisodeData()

# save data
save(list = c("players", "episodes"), file = "ChaseData.Rdata")
```

Load data from previously scraped data
```{r load data}
library(tidyverse)
load(file = "ChaseData.Rdata")
```

How often are low, mid, and high offers taken
```{r}
offers <- players %>%
  select(c(CashBuilder,LowerOffer,HigherOffer,ChosenOffer)) %>% 
  mutate(OfferTaken = case_when(
    ChosenOffer == LowerOffer ~ "Lower",
    ChosenOffer == CashBuilder ~ "Middle",
    ChosenOffer == HigherOffer ~ "Higher"
  )) %>%
  group_by(OfferTaken) %>% 
  summarise(
    number_taken = n()
  ) %>% 
  mutate(percent = prop.table(number_taken))
```

Graph of average high offer and lower offer by cashbuilder
```{r}
plot_data <- players %>% 
    mutate(OfferTaken = case_when(
    ChosenOffer == LowerOffer ~ "Lower",
    ChosenOffer == CashBuilder ~ "Middle",
    ChosenOffer == HigherOffer ~ "Higher"
  ))

low_high_by_CashBuilder <- players %>%
  group_by(CashBuilder) %>% 
  summarise(
    avg_low = mean(LowerOffer,na.rm = TRUE),
    avg_high = mean(HigherOffer),
    med_low = median(LowerOffer,na.rm = TRUE),
    med_high = median(HigherOffer)
  )

ggplot()+
  geom_point(data =players, aes(x = CashBuilder, y = LowerOffer), color = "red")+
  geom_point(data =players, aes(x = CashBuilder, y = HigherOffer), color = "purple")+
  geom_line(data = low_high_by_CashBuilder, aes(x= CashBuilder, y = avg_low), color = "red")+
  geom_line(data = low_high_by_CashBuilder, aes(x= CashBuilder, y = avg_high), color = "purple")+
  geom_line(data = low_high_by_CashBuilder, aes(x= CashBuilder, y = CashBuilder))
```

Likelihood of taking high offer based on high offer
```{r}
library(scales)
source("custom_gg.R")

# custom colors
my_colors = c("#207561", "#589167", "#a0cc78")

# cuts to use in bar graph
high_offer_cuts =  c(
  0, 10000, 20000, 30000, 40000, 50000, 60000, 70000, 80000, 90000, 100000, Inf)
high_offer_breaks = c("(0,1e+04]","(1e+04,2e+04]","(2e+04,3e+04]","(3e+04,4e+04]", "(4e+04,5e+04]",
                      "(5e+04,6e+04]", "(6e+04,7e+04]", "(7e+04,8e+04]", "(8e+04,9e+04]",
                      "(9e+04,1e+05]", "(1e+05,Inf]")
high_offer_labels = c("≤10k", "10-20k", "20-30k","30-40k","40-50k","50-60k","60-70k","70-80k",
                      "80-90k","90-100k",">100k")

plot_data <- players %>% 
    mutate(OfferTaken = case_when(
    ChosenOffer == LowerOffer ~ "Lower",
    ChosenOffer == CashBuilder ~ "Middle",
    ChosenOffer == HigherOffer ~ "Higher"
  )) %>% 
  mutate(cuts = cut(HigherOffer, high_offer_cuts)) %>% 
  group_by(cuts, OfferTaken) %>% 
  summarise(count = n())

plot_data$OfferTaken <- factor(plot_data$OfferTaken, levels = c("Higher", "Middle", "Lower"))

ggplot(plot_data, aes(fill=OfferTaken, y=count, x=cuts)) + 
  geom_bar(position="fill", stat="identity")+
  scale_fill_manual(values = my_colors)+
  scale_x_discrete(breaks = high_offer_breaks,
                   labels= high_offer_labels)+
  xlab("Higher Offer Value (£)") +
  labs(fill = "OFFER TAKEN")+
  ggtitle("How enticing is the higher offer?") +
  
  scale_y_continuous(name = "Percentage of time offer is taken", labels = percent, expand = c(-1,1) )+
  theme_campbead()
```



